### ISSUE TITLE
Getting errors for web build

### ISSUE THREAD

**Issue by songproducer** [haorendashu/nostrmo_faq#4]
```
GET file:///assets/packages/flutter_inappwebview/assets/web/web_support.js net::ERR_FILE_NOT_FOUND
```

```
flutter.js:3    
       GET file:///Users/leotreasure/nostrmo/web/$FLUTTER_BASE_HREF/main.dart.js net::ERR_FILE_NOT_FOUND
```

```
flutter.js:3 Exception while loading service worker: TypeError: Failed to register a ServiceWorker: The URL protocol of the current origin ('null') is not supported.
    at g.loadServiceWorker (flutter.js:3:315)
    at v.loadEntrypoint (flutter.js:3:2459)
    at index.html:62:23
    ```

**Comment by haorendashu** [comment]
Fix thanks.

**Comment by songproducer** [comment]
Sorry, I still struggle to get it working after building for web.

I just see the letter N and in the console:

<img width="1573" alt="Screenshot 2024-04-08 at 9 44 29 PM" src="https://github.com/haorendashu/nostrmo_faq/assets/597346/f7d8eb37-4dea-40db-9765-701254b6fe29">

**Comment by haorendashu** [comment]
Maybe you can try the web version throw a domain or just this url https://web.nostrmo.com/
